---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: owncloudci/alpine
  commands:
  - make doc

- name: sync
  image: thegeeklab/git-batch
  commands:
  - git-batch

- name: markdownlint
  image: node:lts-alpine
  commands:
  - npm install -g markdownlint-cli
  - markdownlint -p .gitignore 'content/**/*.md' 'README.md'

- name: spellcheck
  image: node:lts-alpine
  commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'content/**/*.md' 'README.md' -d .dictionary -p spell indefinite-article syntax-urls frontmatter --frontmatter-keys title --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error

- name: build
  image: owncloudci/hugo:0.85.0
  commands:
  - hugo

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    password:
      from_secret: github_token
    target_branch: master
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack:1
  settings:
    channel:
      from_secret: slack_channel
    webhook:
      from_secret: slack_webhook_private

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- build

---
kind: signature
hmac: bdd0465537291e16aceaa69ee361e5f8040ad827c79fbde5c26a37c70a3cc6bd

...
