---
kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:0.59.1-alpine
  commands:
    - hugo-official --theme dot
    - ls -l
  when:
    ref:
      - refs/heads/source
      - "refs/pull/**"

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source
---
kind: signature
hmac: 5483d0a4c214d8babeaef4b2d1a6a1fe0da047dbaddba14e8f28189bd074a041

...
