---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: owncloudci/alpine
  commands:
  - make doc

- name: sync
  image: thegeeklab/git-batch
  commands:
  - git-batch

- name: build
  image: owncloudci/hugo:0.83.1
  commands:
  - hugo

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    password:
      from_secret: github_token
    target_branch: master
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**

---
kind: signature
hmac: f417e282d4d9e660b38994de3aaad8c4f73f6c66893cd33241961f8e10237644

...
