---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: byrnedo/alpine-curl
  commands:
  - mkdir -p themes/hugo-geekdoc/
  - curl -L https://github.com/xoxys/hugo-geekdoc/releases/download/v0.3.1/hugo-geekdoc.tar.gz | tar -xz -C themes/hugo-geekdoc/ --strip-components=1

- name: sync
  image: xoxys/git-batch:latest
  commands:
  - git-batch

- name: build
  image: klakegg/hugo:0.72.0-ext-alpine
  commands:
  - hugo-official

- name: publish
  image: plugins/gh-pages:latest
  settings:
    pages_directory: public/
    password:
      from_secret: github_token
    target_branch: master
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**

---
kind: signature
hmac: 791d20288a6358e75de114e39ff14b7038a81020e6da02446f977efd40f3fdd9

...
