---
kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:0.59.1-alpine
  commands:
    - hugo --theme dot
    - ls -l
  environment:
    HUGO_DESTINATION: ./public
  when:
    ref:
      - refs/heads/source
      - "refs/pull/**"

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source
---
kind: signature
hmac: 57e54c3ebb55f30bedf03ecfbe911f8dcfcbced3673d1860bc33d985899ae44c

...
