---
kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:0.59.1-alpine
  commands:
    - hugo --theme dot
  when:
    ref:
      - refs/heads/source
      - "refs/pull/**"

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source
---
kind: signature
hmac: fe0680aeb4200574685ade260f36a5be8b83e40a4f5764c7540667fc8888910e

...
