---
kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:0.59.1-alpine
  commands:
    - hugo-official --theme dot
  when:
    ref:
      - refs/heads/source
      - "refs/pull/**"

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source
---
kind: signature
hmac: b1d0302986d815d3eb4c525d137fb2d66c1fbfefce8af3d1ee31e39d655f129a

...
