---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: owncloudci/alpine
  commands:
  - make doc

- name: sync
  image: thegeeklab/git-batch
  commands:
  - git-batch

- name: build
  image: klakegg/hugo:0.81.0-ext-alpine
  commands:
  - hugo-official

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    password:
      from_secret: github_token
    target_branch: master
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**

---
kind: signature
hmac: 987d187efa163b5a9d9626a72cd26db27c2006209e1edf0d6a53b72ffb7a9824

...
