---
kind: pipeline
name: default

steps:
- name: sync
  image: alpine/git:latest
  commands:
    - git clone https://github.com/owncloud-ansible/owncloud --branch docs --single-branch content/role/owncloud
    #- git clone https://github.com/owncloud-ansible/redis --branch docs --single-branch content/role/redis
    #- git clone https://github.com/owncloud-ansible/php --branch docs --single-branch content/role/php
    #- git clone https://github.com/owncloud-ansible/mariadb --branch docs --single-branch content/role/mariadb
    #- git clone https://github.com/owncloud-ansible/apache --branch docs --single-branch content/role/apache

- name: build
  image: klakegg/hugo:0.59.1-alpine
  commands:
    - hugo-official --theme dot

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**
---
kind: signature
hmac: 9f6dddf2c73d8934ac4aa51064be1f95682e078d7706f45d684cfec41990811a

...
