---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: byrnedo/alpine-curl
  commands:
  - mkdir -p themes/hugo-geekdoc/
  - curl -sSL https://github.com/thegeeklab/hugo-geekdoc/releases/download/v0.5.0/hugo-geekdoc.tar.gz | tar -xz -C themes/hugo-geekdoc/ --strip-components=1

- name: sync
  image: thegeeklab/git-batch
  commands:
  - git-batch

- name: build
  image: klakegg/hugo:0.78.0-ext-alpine
  commands:
  - hugo-official

- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: public/
    password:
      from_secret: github_token
    target_branch: master
    username:
      from_secret: github_username
  when:
    ref:
    - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**

---
kind: signature
hmac: 697b0058879056b1ae18b5a6f5992794a54c08e805fd06c905c0a30d34b7f93e

...
