---
kind: pipeline
name: default

concurrency:
  limit: 1

steps:
- name: sync
  image: xoxys/git-batch:latest
  commands:
    - git-batch

- name: build
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
    - hugo-official

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**
---
kind: signature
hmac: 5f6c06cdff36a2f33bf83299eb7f910b6feeccd01a2470b2aeb5de39d0f3ded4

...
