---
kind: pipeline
name: default

steps:
- name: build
  image: klakegg/0.59.1-alpine
  commands:
    - hugo --theme dot
  when:
    ref:
      - refs/heads/source
      - "refs/pull/**"

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source
---
kind: signature
hmac: 83bc9677c23595c4f75ad2be21e359339572faa0495ea9248cf9a51f533d3671

...
