---
kind: pipeline
name: default

steps:
- name: sync
  image: alpine/git:latest
  commands:
    - git clone https://github.com/owncloud-ansible/owncloud --branch docs --single-branch content/role/owncloud

- name: build
  image: klakegg/hugo:0.59.1-alpine
  commands:
    - hugo-official --theme dot

- name: publish
  image: plugins/gh-pages:latest
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public/
    target_branch: master
  when:
    ref:
      - refs/heads/source

trigger:
  ref:
  - refs/heads/source
  - refs/pull/**
---
kind: signature
hmac: 3c2d2ecfdb21b041120c1ebba82f5783d8207927dbabe31e486666a50cb26564

...
