---
baseURL: "https://owncloud-ansible.github.io/"
languageCode: "en-us"
title: "Ansible"
theme: "hugo-geekdoc"

pygmentsUseClasses: true
pygmentsCodefences: true

disablePathToLower: true

params:
  geekdocToC: 3
  geekdocLogo: logo.png
  geekdocBreadcrumb: true
  geekdocDateFormat: "Jan 2, 2006"
  geekdocSearch: true
  geekdocLegalNotice: https://owncloud.org/imprint/
  geekdocPrivacyPolicy: https://owncloud.org/privacy-policy/
  geekdocAnchor: true
  geekdocAnchorLeft: true
  geekdocAnchorCopy: true
