baseURL = "https://owncloud-ansible.github.io/"
languageCode = "en-us"
title = "ownCloud Ansible"

theme = "book"
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
  BookToC = false
  BookSection = '*'

  BookLogo = 'logo.svg'
